[tool.poetry]
name = "bindsnet"
version = "0.3.2"
description = "Spiking neural networks for ML in Python"
authors = [ "Hananel Hazan <hananel@hazan.org.il>", "Daniel Saunders", "Darpan Sanghavi", "Hassaan Khan" ]
license = "AGPL-3.0-only"
readme = "README.md"
repository = "https://github.com/BindsNET/bindsnet"
documentation = "https://bindsnet-docs.readthedocs.io/"
keywords = ["spiking", "neural", "networks", "pytorch"]

[tool.poetry.dependencies]
python = ">=3.8.1,<3.11"
numpy = "^1.24.3"
scipy = "^1.10.1"
Cython = "^0.29.33"
torch = "2.0.1+cu118"
torchvision = "0.15.2+cu118"
torchaudio = "2.0.2+cu118"
tensorboardX = "2.6.1"
tqdm = "^4.65.0"
matplotlib = "^3.7.1"
gymnasium = "^0.28.1"
scikit-build = "^0.17.6"
scikit-image = "^0.21.0"
scikit-learn = "^1.2.2"
opencv-python = "^4.7.0.72"
pandas = "^2.0.2"
foolbox = "^3.3.3"

[tool.poetry.dev-dependencies]
pytest = "^7.2.2"
pre-commit = "^2.14.0"
notebook = "^6.4.12"
jupyterlab = "^3.4.5"
isort = "^5.9.3"
black = "^23.1.0"
autoflake = "^2.0.1"

Sphinx = "3.4.3"
sphinx-rtd-theme = "0.5.1"
imagecodecs = "^2021.8.26"

[build-system]
requires = ["setuptools", "poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"
line_length = 88
src_paths = ["bindsnet", "test"]

[tool.black]
target-version = ['py38']
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.pytest_cache
  | \.venv
  | \.github
  | build
  | dist
  | BindsNET.egg-info
  | notebooks
  | data
  | logs
  )/
'''
